# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .notebook_cell import NotebookCell
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import pydantic


class Notebook(UniversalBaseModel):
    id: str
    name: str
    kernel_name: str
    cells: typing.List[NotebookCell]
    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
