# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.models.fetch_html_response import FetchHtmlResponse

class TestFetchHtmlResponse(unittest.TestCase):
    """FetchHtmlResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FetchHtmlResponse:
        """Test FetchHtmlResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FetchHtmlResponse`
        """
        model = FetchHtmlResponse()
        if include_optional:
            return FetchHtmlResponse(
                html = ''
            )
        else:
            return FetchHtmlResponse(
        )
        """

    def testFetchHtmlResponse(self):
        """Test FetchHtmlResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
