# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.models.execute_script_response import ExecuteScriptResponse

class TestExecuteScriptResponse(unittest.TestCase):
    """ExecuteScriptResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExecuteScriptResponse:
        """Test ExecuteScriptResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExecuteScriptResponse`
        """
        model = ExecuteScriptResponse()
        if include_optional:
            return ExecuteScriptResponse(
                status = '',
                status_description = '',
                result = scrapybara.models.result.result(),
                streaming = True
            )
        else:
            return ExecuteScriptResponse(
                status = '',
                status_description = '',
                result = scrapybara.models.result.result(),
                streaming = True,
        )
        """

    def testExecuteScriptResponse(self):
        """Test ExecuteScriptResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
