# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.models.generate_script_request import GenerateScriptRequest

class TestGenerateScriptRequest(unittest.TestCase):
    """GenerateScriptRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GenerateScriptRequest:
        """Test GenerateScriptRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GenerateScriptRequest`
        """
        model = GenerateScriptRequest()
        if include_optional:
            return GenerateScriptRequest(
                url = '',
                command = '',
                steps = [
                    ''
                    ],
                streaming = True,
                input_schema = None,
                output_schema = None
            )
        else:
            return GenerateScriptRequest(
                url = '',
                command = '',
        )
        """

    def testGenerateScriptRequest(self):
        """Test GenerateScriptRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
