# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.api.helpers_api import HelpersApi


class TestHelpersApi(unittest.TestCase):
    """HelpersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HelpersApi()

    def tearDown(self) -> None:
        pass

    def test_fetch_html(self) -> None:
        """Test case for fetch_html

        Fetch HTML
        """
        pass


if __name__ == '__main__':
    unittest.main()
