# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.api.script_generation_api import ScriptGenerationApi


class TestScriptGenerationApi(unittest.TestCase):
    """ScriptGenerationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScriptGenerationApi()

    def tearDown(self) -> None:
        pass

    def test_generate_script(self) -> None:
        """Test case for generate_script

        Generate script
        """
        pass


if __name__ == '__main__':
    unittest.main()
