# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from scrapybara.api.script_management_api import ScriptManagementApi


class TestScriptManagementApi(unittest.TestCase):
    """ScriptManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ScriptManagementApi()

    def tearDown(self) -> None:
        pass

    def test_delete_script(self) -> None:
        """Test case for delete_script

        Delete script
        """
        pass

    def test_get_script(self) -> None:
        """Test case for get_script

        Get script
        """
        pass


if __name__ == '__main__':
    unittest.main()
