# coding: utf-8

# flake8: noqa
"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from scrapybara.models.execute_script_request import ExecuteScriptRequest
from scrapybara.models.execute_script_response import ExecuteScriptResponse
from scrapybara.models.fetch_html_request import FetchHtmlRequest
from scrapybara.models.fetch_html_response import FetchHtmlResponse
from scrapybara.models.generate_script_request import GenerateScriptRequest
from scrapybara.models.generate_script_response import GenerateScriptResponse
from scrapybara.models.get_script_response import GetScriptResponse
