# coding: utf-8

"""
    Scrapybara API

    Scrapybara API provides web automation, capybara-style. It allows users to generate, execute, and manage scripts.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GenerateScriptStreamingResponse(BaseModel):
    """
    GenerateScriptStreamingResponse
    """ # noqa: E501
    script_id: StrictStr = Field(description="Unique identifier for the generated script.")
    status: StrictStr = Field(description="The current status of script generation (e.g., 'in_progress', 'completed', 'error').")
    status_description: StrictStr = Field(description="Additional details about the generation status or errors.")
    current_script: Optional[StrictStr] = Field(default=None, description="The current version of the generated script.")
    current_script_execution_result: Optional[StrictStr] = Field(default=None, description="The result of executing the current version of the script.")
    reasoning: Optional[StrictStr] = Field(default=None, description="Explanation of the reasoning behind the current script version.")
    streaming: StrictBool
    __properties: ClassVar[List[str]] = ["script_id", "status", "status_description", "current_script", "current_script_execution_result", "reasoning", "streaming"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GenerateScriptStreamingResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GenerateScriptStreamingResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "script_id": obj.get("script_id"),
            "status": obj.get("status"),
            "status_description": obj.get("status_description"),
            "current_script": obj.get("current_script"),
            "current_script_execution_result": obj.get("current_script_execution_result"),
            "reasoning": obj.get("reasoning"),
            "streaming": obj.get("streaming")
        })
        return _obj


